### PR TITLE
Updated argument order for addWicket.

### PR DESCRIPTION
**Pull request by jrobind**
@ryansmith94 
Great job on Scorebook! I stumbled across it a few weeks ago - its been a pleasure reading through the code. I hope you don't mind this pull request (it's my first one!).

As for the pull request: Regarding addWicket() according to the documentation the first argument should be the batsman object, the second should be the 'howOut' string, and the third, and final argument should be an optional fielder object. 

However, the batsman object and the 'howOut' string are being appended to the wicket object in the wrong order:

`book.addWicket({name: 'batsmanName'}, 'LBW') //  returns  {batsman: 'LBW', howOut: {name: 'batsmanName' }};`

I have updated the argument order, and also updated the relevant addWicket() test which now passes. Please let me know if there's anything that I can further clarify in my PR. Thanks!

### CODE REVIEW

**Comment by ryansmith94** [comment]
Hey @JrobinWebDev thanks for your kind feedback and generously taking the time to make this pull request, I certainly don't mind.

I think the purpose of how out going first in the arguments was to make the batsman an optional argument since the batsman can usually be figured out automatically.

I'll review this PR now 👍

**Review by ryasmi — APPROVED** [review]

**Comment by ryansmith94** [comment]
Ok this looks great, thanks again @JrobinWebDev. I'll merge this now and release this as version 3 (since it potentially breaks some existing applications that were passing the arguments the other way around).

**Comment by ryasmi** [comment]
Just published it to NPM 👍

**Comment by jrobind** [comment]
@ryansmith94 That's awesome news! Thank you for the merge! :+1:

**Comment by ryasmi** [comment]
No worries @JrobinWebDev 👍

**Pull request merged**
